
import re, json, openpyxl
from collections import defaultdict, Counter
from pathlib import Path

SRC = Path('/Users/hosen/Library/Containers/com.tencent.WeWorkMac/Data/Documents/Profiles/7C21D360DBFA836768191953082E98DB/Caches/Files/2026-06/781fd32262d3ebf3a9762247d5be4003/DE广告搜索词近365天.xlsx')
OUT_DIR = Path('/Users/hosen/Documents/Amazon/keyword_library')
OUT_DIR.mkdir(parents=True, exist_ok=True)

# ── Attribute normalization map ──
# Maps raw attribute fragments to canonical attribute names
ATTR_MAP = {
    # Case/hülle
    "hülle": "Hülle", "huelle": "Hülle", "case": "Hülle", "cover": "Hülle",
    "handyhülle": "Hülle", "handy hülle": "Hülle", "handyhu00fclle": "Hülle",
    "handycase": "Hülle", "handy case": "Hülle", "handy cover": "Hülle",
    "handycover": "Hülle", "schutzhülle": "Hülle", "schutzcover": "Hülle",
    "schutzhuelle": "Hülle", "schale": "Hülle", "handyschale": "Hülle",
    "etui": "Hülle", "hullen": "Hülle", "hu00fclle": "Hülle",
    "backcover": "Hülle", "back cover": "Hülle",
    "telefonhülle": "Hülle", "smartphone hülle": "Hülle",
    "vollhülle": "Hülle", "vollschutzhülle": "Hülle",
    "rundum hülle": "Hülle", "ganzkörperhülle": "Hülle",
    "outdoorhülle": "Hülle", "outdoor hülle": "Hülle",
    "outdoorhuelle": "Hülle", "outdor": "Hülle",
    "panzerhülle": "Hülle", "panzer hülle": "Hülle",
    "hardcase": "Hülle", "hard case": "Hülle", "hardcover": "Hülle",
    "bumper": "Hülle", "tank case": "Hülle",
    "silikonhülle": "Hülle", "silikon hülle": "Hülle",
    "lederhülle": "Hülle", "metallhülle": "Hülle", "metal case": "Hülle",
    "alu case": "Hülle", "aluminum case": "Hülle", "aluminium": "Hülle",
    "carbon hülle": "Hülle", "holzhülle": "Hülle",
    "flipcase": "Hülle", "klapphülle": "Hülle",
    "rugged case": "Hülle", "rugged": "Hülle",
    "military": "Hülle", "militär": "Hülle", "militärisch": "Hülle",
    "stoßfest": "Hülle", "stoßfeste": "Hülle", "shockproof": "Hülle",
    "sturzsicher": "Hülle", "robust": "Hülle", "robuste": "Hülle",
    "stabil": "Hülle", "armored": "Hülle",
    "wasserdicht": "Hülle", "wasserfeste": "Hülle", "waterproof": "Hülle",
    "dünne": "Hülle", "dünn": "Hülle", "ultra dünn": "Hülle",
    "durchsichtig": "Hülle", "transparent": "Hülle", "klar": "Hülle",
    "silikon": "Hülle", "silicone": "Hülle",
    "kratzfeste": "Hülle", "kratzfest": "Hülle",
    "staubschutz": "Hülle", "dust plug": "Hülle", "dustproof": "Hülle",
    "komplettschutz": "Hülle", "komplett": "Hülle", "rundumschutz": "Hülle",
    "vollschutz": "Hülle", "fullbody": "Hülle",
    "schutzhülle": "Hülle", "schutzcover": "Hülle",
    "handytasche": "Hülle", "tasche": "Hülle",
    "organizer": "Hülle",
}

ATTR_MAP.update({
    # Stand/Ständer
    "ständer": "Ständer", "ständer": "Ständer", "stand": "Ständer",
    "stander": "Ständer", "staender": "Ständer", "standfuß": "Ständer",
    "standfuss": "Ständer", "standfu00df": "Ständer",
    "kickstand": "Ständer", "kick stand": "Ständer",
    "aufsteller": "Ständer", "aufstellen": "Ständer", "stehend": "Ständer",
    "hinstellen": "Ständer", "stütze": "Ständer",
    "halterung": "Ständer", "halter": "Ständer", "halten": "Ständer",
    "fingerhalter": "Ständer", "fingerhalterung": "Ständer",
    "finger ring": "Ständer", "fingerring": "Ständer",
    "pop grip": "Ständer", "popsocket": "Ständer",
    "griff": "Ständer", "mit griff": "Ständer",
    "ringständer": "Ständer", "ring ständer": "Ständer",
    "standring": "Ständer", "ringhalter": "Ständer",
    "ringhalterung": "Ständer", "ring ständer": "Ständer",
    "drehständer": "Ständer", "drehbarer": "Ständer",
    "360 grad": "Ständer", "360°": "Ständer", "360grad": "Ständer",
    "360 degree": "Ständer", "rotating": "Ständer",
    "drehbare": "Ständer", "drehbar": "Ständer",
    "180 degree": "Ständer",
    "integriertem ständer": "Ständer",
    "phone case mit integriertem ständer": "Ständer",
    "stand case": "Ständer", "stand handyhülle": "Ständer",
    "standing": "Ständer", "ständer design": "Ständer",
    "ständerhülle": "Ständer", "stand hülle": "Ständer",
    "ständer ohne ring": "Ständer",
    "hülle zum aufstellen": "Ständer",
    "hülle und ständer": "Ständer",
    "mit ständer": "Ständer",
    "mit standfuß": "Ständer", "mit standfuss": "Ständer",
    "mit aufsteller": "Ständer",
    "mit halterung": "Ständer", "mit halter": "Ständer",
    "mit fingerhalter": "Ständer", "mit fingerhalterung": "Ständer",
    "mit griff": "Ständer",
    "mit ringhalter": "Ständer", "mit ringhalterung": "Ständer",
    "mit integriertem ständer": "Ständer",
    "zum aufstellen": "Ständer", "zum hinstellen": "Ständer",
    "case aufstellen": "Ständer", "case with stand": "Ständer",
    "case stand": "Ständer", "case with kick stand": "Ständer",
    "hülle ständer": "Ständer", "ständer hülle": "Ständer",
    "standfuß": "Ständer", "standfuss": "Ständer",
    "ständer magnetisch": "Ständer",
    "ständer ring": "Ständer", "ring ständer": "Ständer",
    "ständerhalterung": "Ständer",
    "popup": "Ständer", "pop up": "Ständer",
    "verstellbarem kickstand": "Ständer",
    "adjustable stand": "Ständer",
    "dual stand": "Ständer",
    "phone case with stand": "Ständer",
    "hülle mit stütze": "Ständer",
    "ständer ohne ring": "Ständer",
    "mit band und ständer": "Ständer",
    "mit band und ring": "Ständer",
    "mit ständer und halterung": "Ständer",
    "mit ständerhalterung": "Ständer",
    "hülle mit standfuß": "Ständer",
    "case mit ständer": "Ständer",
    "stand case": "Ständer",
    "case with stand and screen protection": "Ständer",
    "case with wireless charging": "Ständer",
    "case with adjustable stand": "Ständer",
})

ATTR_MAP.update({
    # MagSafe/Magnet
    "magsafe": "MagSafe", "mag safe": "MagSafe", "mag save": "MagSafe",
    "magnet": "MagSafe", "magnetisch": "MagSafe", "magnetic": "MagSafe",
    "magnetische": "MagSafe", "magnetischer": "MagSafe",
    "magnetring": "MagSafe", "magnet ring": "MagSafe",
    "magnethülle": "MagSafe", "magnet hülle": "MagSafe",
    "magnet cover": "MagSafe", "magnetic case": "MagSafe",
    "magnetische hülle": "MagSafe", "magnetisch hülle": "MagSafe",
    "magnetische adsorption": "MagSafe",
    "magnetisch verschließbar": "MagSafe",
    "magnethalter": "MagSafe", "magnethalterung": "MagSafe",
    "magnet und kette": "MagSafe",
    "magnet und halter": "MagSafe",
    "magnet und versteckte ständer": "MagSafe",
    "mit magnet": "MagSafe", "mit magsafe": "MagSafe",
    "mit magnetring": "MagSafe",
    "magsafe hülle": "MagSafe", "magsafe case": "MagSafe",
    "magsafe ständer": "MagSafe", "magsafe stand": "MagSafe",
    "magsafe ring": "MagSafe", "magsafe ringständer": "MagSafe",
    "magsafe und ständer": "MagSafe",
    "magsafe mit ständer": "MagSafe",
    "magsafe mit ring": "MagSafe",
    "magsafe ring ständer": "MagSafe",
    "magsafe ständer": "MagSafe",
    "magsafe mit halter": "MagSafe",
    "magsafe mit halterung": "MagSafe",
    "magsafe fingerhalter": "MagSafe",
    "magsafe kartenhalter": "MagSafe",
    "magsafe ladegerät": "MagSafe",
    "magsafe powerbank": "MagSafe",
    "magsafe wallet": "MagSafe",
    "magsafe orange": "MagSafe",
    "magsafe ring in case": "MagSafe",
    "magsafehülle": "MagSafe",
    "magsafe-hülle": "MagSafe",
    "magsafe und halterung": "MagSafe",
    "magsafe zum aufstellen": "MagSafe",
    "magsafe set": "MagSafe",
    "magsafe stabil": "MagSafe",
    "magsafe deutschland": "MagSafe",
    "magsafe spigen": "MagSafe",
    "magsafe torras": "MagSafe",
    "magsafe otterbox": "MagSafe",
    "magsafe outdoor": "MagSafe",
    "magsafe stoßfest": "MagSafe",
    "magsafe 360": "MagSafe", "magsafe 360 grad": "MagSafe",
    "magsafe standing": "MagSafe",
    "magsafe farbig": "MagSafe",
    "magsafe ruggedized": "MagSafe",
    "magsafe case stand": "MagSafe",
    "magsafe stand": "MagSafe",
    "magsafe ständer grün": "MagSafe",
    "magsafe ständer rot": "MagSafe",
    "magsafe mit kameraschutz": "MagSafe",
    "magsafe mit ständer und kameraschutz": "MagSafe",
    "magsafe mit ring und ständer": "MagSafe",
    "magsafe ring und ständer": "MagSafe",
    "magsafe ring ständer": "MagSafe",
    "magsafe ständer ring": "MagSafe",
    "magsafe mit ständer magnetisch": "MagSafe",
    "magsafe ständer magnetisch": "MagSafe",
    "magsafe magnetisch": "MagSafe",
    "magsafe magnetisch mit ständer": "MagSafe",
    "magsafe mit magnet": "MagSafe",
    "magsafe mit magnet und ständer": "MagSafe",
    "magsafe und magnet": "MagSafe",
    "magsafe ring magnetisch": "MagSafe",
    "magsafe mit ring magnetisch": "MagSafe",
    "magsafe ring ständer magnetisch": "MagSafe",
    "magsafe ring und magnet": "MagSafe",
    "magsafe 360 grad ring ständer": "MagSafe",
    "magsafe 360° drehbarer ring ständer": "MagSafe",
    "magsafe 360 grad drehbarer ring": "MagSafe",
    "magsafe 360 grad drehbar": "MagSafe",
    "magsafe 360 grad hülle": "MagSafe",
    "magsafe 360 grad ständer": "MagSafe",
    "magsafe 360° drehbarer ständer": "MagSafe",
    "magsafe 360°": "MagSafe",
    "magsafe ring 360": "MagSafe",
    "magsafe ring 360 grad": "MagSafe",
    "magsafe ständer 360 grad": "MagSafe",
    "magsafe mit 360 grad ring": "MagSafe",
    "magsafe mit 360° drehbarer ring": "MagSafe",
    "magsafe mit 360 grad ständer": "MagSafe",
    "magsafe mit 360° drehbarer ständer": "MagSafe",
    "magsafe mit 360 grad ring ständer": "MagSafe",
    "magsafe 360 grad handyhülle": "MagSafe",
    "magsafe 360 grad hülle mit ring": "MagSafe",
    "magsafe 360 grad hülle mit ständer": "MagSafe",
    "magsafe 360 grad hülle magnetisch": "MagSafe",
    "magsafe 360 grad hülle mit ring ständer": "MagSafe",
    "magsafe 360 grad ständer hülle": "MagSafe",
    "magsafe 360 grad ständer ring": "MagSafe",
    "magsafe 360 grad ring ständer hülle": "MagSafe",
    "magsafe 360 grad ring ständer magnetisch": "MagSafe",
    "magsafe 360 grad drehbarer ring ständer hülle": "MagSafe",
    "magsafe 360 grad drehbarer ring ständer magnetisch": "MagSafe",
    "magsafe 360 grad drehbarer ständer ring": "MagSafe",
    "magsafe 360 grad drehbarer ständer ring hülle": "MagSafe",
    "magsafe 360 grad drehbarer ständer ring magnetisch": "MagSafe",
    "magsafe 360 grad drehbarer ring ständer hülle magnetisch": "MagSafe",
    "magsafe 360 grad drehbarer ständer ring hülle magnetisch": "MagSafe",
    "magsafe 360 grad drehbarer ring ständer magnetisch hülle": "MagSafe",
    "magsafe 360 grad drehbarer ständer ring magnetisch hülle": "MagSafe",
    "magsafe 360 grad drehbarer ring ständer hülle magnetisch stoßfest": "MagSafe",
    "magsafe 360 grad drehbarer ständer ring hülle magnetisch stoßfest": "MagSafe",
    "magsafe 360 grad drehbarer ring ständer magnetisch hülle stoßfest": "MagSafe",
    "magsafe 360 grad drehbarer ständer ring magnetisch hülle stoßfest": "MagSafe",
    "magsafe 360 grad drehbarer ring ständer hülle stoßfest magnetisch": "MagSafe",
    "magsafe 360 grad drehbarer ständer ring hülle stoßfest magnetisch": "MagSafe",
    "magsafe 360 grad drehbarer ring ständer magnetisch stoßfest hülle": "MagSafe",
    "magsafe 360 grad drehbarer ständer ring magnetisch stoßfest hülle": "MagSafe",
})

ATTR_MAP.update({
    # Ring
    "ring": "Ring", "ringe": "Ring",
    "mit ring": "Ring", "ring hülle": "Ring",
    "ringhalter": "Ring", "ringhalterung": "Ring",
    "ring ständer": "Ring", "ständer ring": "Ring",
    "ring magnetisch": "Ring", "ring magnet": "Ring",
    "ring und magsafe": "Ring", "ring und magnet": "Ring",
    "ring und ständer": "Ring",
    "ring ständer magnetisch": "Ring",
    "ring ständer hülle": "Ring",
    "ring hülle ständer": "Ring",
    "ring ständer hülle magnetisch": "Ring",
    "ring hülle ständer magnetisch": "Ring",
    "ring magnetisch hülle": "Ring",
    "ring magnetisch hülle ständer": "Ring",
    "ring hülle magnetisch ständer": "Ring",
    "ring ständer magnetisch hülle": "Ring",
    "ringhalterung ständer": "Ring",
    "ringhalterung magnetisch": "Ring",
    "ringhalterung ständer magnetisch": "Ring",
    "ringhalterung magnetisch ständer": "Ring",
    "ringhalterung hülle": "Ring",
    "ringhalterung hülle ständer": "Ring",
    "ringhalterung hülle magnetisch": "Ring",
    "ringhalterung hülle ständer magnetisch": "Ring",
    "ringhalterung hülle magnetisch ständer": "Ring",
    "ringhalterung ständer hülle": "Ring",
    "ringhalterung ständer hülle magnetisch": "Ring",
    "ringhalterung ständer magnetisch hülle": "Ring",
    "ringhalterung magnetisch hülle ständer": "Ring",
    "ringhalterung magnetisch ständer hülle": "Ring",
    "doppelring": "Ring",
    "drehbare ring": "Ring",
    "drehbarer ring": "Ring",
    "drehbarer magnet ring": "Ring",
    "360 grad ring": "Ring",
    "360° ring": "Ring",
    "360 grad drehbarer ring": "Ring",
    "360° drehbarer ring": "Ring",
    "360 grad ring ständer": "Ring",
    "360° ring ständer": "Ring",
    "360 grad drehbarer ring ständer": "Ring",
    "360° drehbarer ring ständer": "Ring",
    "360 grad ring ständer magnetisch": "Ring",
    "360° ring ständer magnetisch": "Ring",
    "360 grad drehbarer ring ständer magnetisch": "Ring",
    "360° drehbarer ring ständer magnetisch": "Ring",
    "360 grad ring ständer hülle": "Ring",
    "360° ring ständer hülle": "Ring",
    "360 grad drehbarer ring ständer hülle": "Ring",
    "360° drehbarer ring ständer hülle": "Ring",
    "360 grad ring ständer hülle magnetisch": "Ring",
    "360° ring ständer hülle magnetisch": "Ring",
    "360 grad drehbarer ring ständer hülle magnetisch": "Ring",
    "360° drehbarer ring ständer hülle magnetisch": "Ring",
    "360 grad ring ständer magnetisch hülle": "Ring",
    "360° ring ständer magnetisch hülle": "Ring",
    "360 grad drehbarer ring ständer magnetisch hülle": "Ring",
    "360° drehbarer ring ständer magnetisch hülle": "Ring",
    "360 grad ring hülle": "Ring",
    "360° ring hülle": "Ring",
    "360 grad drehbarer ring hülle": "Ring",
    "360° drehbarer ring hülle": "Ring",
    "360 grad ring hülle ständer": "Ring",
    "360° ring hülle ständer": "Ring",
    "360 grad drehbarer ring hülle ständer": "Ring",
    "360° drehbarer ring hülle ständer": "Ring",
    "360 grad ring hülle ständer magnetisch": "Ring",
    "360° ring hülle ständer magnetisch": "Ring",
    "360 grad drehbarer ring hülle ständer magnetisch": "Ring",
    "360° drehbarer ring hülle ständer magnetisch": "Ring",
    "360 grad ring hülle magnetisch": "Ring",
    "360° ring hülle magnetisch": "Ring",
    "360 grad drehbarer ring hülle magnetisch": "Ring",
    "360° drehbarer ring hülle magnetisch": "Ring",
    "360 grad ring hülle magnetisch ständer": "Ring",
    "360° ring hülle magnetisch ständer": "Ring",
    "360 grad drehbarer ring hülle magnetisch ständer": "Ring",
    "360° drehbarer ring hülle magnetisch ständer": "Ring",
    "360 grad ring magnetisch": "Ring",
    "360° ring magnetisch": "Ring",
    "360 grad drehbarer ring magnetisch": "Ring",
    "360° drehbarer ring magnetisch": "Ring",
    "360 grad ring magnetisch hülle": "Ring",
    "360° ring magnetisch hülle": "Ring",
    "360 grad drehbarer ring magnetisch hülle": "Ring",
    "360° drehbarer ring magnetisch hülle": "Ring",
    "360 grad ring magnetisch hülle ständer": "Ring",
    "360° ring magnetisch hülle ständer": "Ring",
    "360 grad drehbarer ring magnetisch hülle ständer": "Ring",
    "360° drehbarer ring magnetisch hülle ständer": "Ring",
    "360 grad ring magnetisch ständer": "Ring",
    "360° ring magnetisch ständer": "Ring",
    "360 grad drehbarer ring magnetisch ständer": "Ring",
    "360° drehbarer ring magnetisch ständer": "Ring",
    "360 grad ring magnetisch ständer hülle": "Ring",
    "360° ring magnetisch ständer hülle": "Ring",
    "360 grad drehbarer ring magnetisch ständer hülle": "Ring",
    "360° drehbarer ring magnetisch ständer hülle": "Ring",
    "mit ring und magsafe": "Ring",
    "mit ring und ständer": "Ring",
    "mit ring und magnet": "Ring",
    "mit ring ständer": "Ring",
    "mit ringhalter": "Ring",
    "mit ringhalterung": "Ring",
    "mit ring magnetisch": "Ring",
    "mit ring ständer magnetisch": "Ring",
    "mit ring hülle": "Ring",
    "mit ring hülle ständer": "Ring",
    "mit ring hülle magnetisch": "Ring",
    "mit ring hülle ständer magnetisch": "Ring",
    "mit ring ständer hülle": "Ring",
    "mit ring ständer hülle magnetisch": "Ring",
    "mit ring magnetisch hülle": "Ring",
    "mit ring magnetisch hülle ständer": "Ring",
    "mit ring magnetisch ständer": "Ring",
    "mit ring magnetisch ständer hülle": "Ring",
    "mit ringhalterung ständer": "Ring",
    "mit ringhalterung magnetisch": "Ring",
    "mit ringhalterung hülle": "Ring",
    "mit ringhalterung hülle ständer": "Ring",
    "mit ringhalterung hülle magnetisch": "Ring",
    "mit ringhalterung ständer hülle": "Ring",
    "mit ringhalterung ständer magnetisch": "Ring",
    "mit ringhalterung magnetisch hülle": "Ring",
    "mit ringhalterung magnetisch ständer": "Ring",
    "mit ringhalterung magnetisch hülle ständer": "Ring",
    "mit ringhalterung magnetisch ständer hülle": "Ring",
    "mit 360 grad ring": "Ring",
    "mit 360° ring": "Ring",
    "mit 360 grad drehbarer ring": "Ring",
    "mit 360° drehbarer ring": "Ring",
    "mit 360 grad ring ständer": "Ring",
    "mit 360° ring ständer": "Ring",
    "mit 360 grad drehbarer ring ständer": "Ring",
    "mit 360° drehbarer ring ständer": "Ring",
    "mit 360 grad ring ständer magnetisch": "Ring",
    "mit 360° ring ständer magnetisch": "Ring",
    "mit 360 grad drehbarer ring ständer magnetisch": "Ring",
    "mit 360° drehbarer ring ständer magnetisch": "Ring",
    "mit 360 grad ring hülle": "Ring",
    "mit 360° ring hülle": "Ring",
    "mit 360 grad drehbarer ring hülle": "Ring",
    "mit 360° drehbarer ring hülle": "Ring",
    "mit 360 grad ring hülle ständer": "Ring",
    "mit 360° ring hülle ständer": "Ring",
    "mit 360 grad drehbarer ring hülle ständer": "Ring",
    "mit 360° drehbarer ring hülle ständer": "Ring",
    "mit 360 grad ring hülle magnetisch": "Ring",
    "mit 360° ring hülle magnetisch": "Ring",
    "mit 360 grad drehbarer ring hülle magnetisch": "Ring",
    "mit 360° drehbarer ring hülle magnetisch": "Ring",
    "mit 360 grad ring hülle ständer magnetisch": "Ring",
    "mit 360° ring hülle ständer magnetisch": "Ring",
    "mit 360 grad drehbarer ring hülle ständer magnetisch": "Ring",
    "mit 360° drehbarer ring hülle ständer magnetisch": "Ring",
    "mit 360 grad ring magnetisch": "Ring",
    "mit 360° ring magnetisch": "Ring",
    "mit 360 grad drehbarer ring magnetisch": "Ring",
    "mit 360° drehbarer ring magnetisch": "Ring",
    "mit 360 grad ring magnetisch hülle": "Ring",
    "mit 360° ring magnetisch hülle": "Ring",
    "mit 360 grad drehbarer ring magnetisch hülle": "Ring",
    "mit 360° drehbarer ring magnetisch hülle": "Ring",
    "mit 360 grad ring magnetisch ständer": "Ring",
    "mit 360° ring magnetisch ständer": "Ring",
    "mit 360 grad drehbarer ring magnetisch ständer": "Ring",
    "mit 360° drehbarer ring magnetisch ständer": "Ring",
    "mit 360 grad ring magnetisch hülle ständer": "Ring",
    "mit 360° ring magnetisch hülle ständer": "Ring",
    "mit 360 grad drehbarer ring magnetisch hülle ständer": "Ring",
    "mit 360° drehbarer ring magnetisch hülle ständer": "Ring",
    "mit 360 grad ring magnetisch ständer hülle": "Ring",
    "mit 360° ring magnetisch ständer hülle": "Ring",
    "mit 360 grad drehbarer ring magnetisch ständer hülle": "Ring",
    "mit 360° drehbarer ring magnetisch ständer hülle": "Ring",
    "ring für": "Ring",
    "ring case": "Ring",
    "case ring": "Ring",
    "case mit ring": "Ring",
    "case with ring": "Ring",
    "phone ring": "Ring",
    "galaxy ring": "Ring",
    "ringke": "Ring",
    "magsafe ring": "Ring",
    "ring magsafe": "Ring",
    "ring magnet": "Ring",
    "magnet ring": "Ring",
    "ring induction": "Ring",
    "ring induktion": "Ring",
    "ring und induktion": "Ring",
    "ring induktives laden": "Ring",
    "ring kabelloses laden": "Ring",
    "ring qi": "Ring",
    "ring ladefunktion": "Ring",
    "ring laden": "Ring",
    "ring wireless charging": "Ring",
    "ring inductive charging": "Ring",
})
